apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: spring-api-consumer
        image: spring-api-consumer:1.0.0
        ports:
        - containerPort: 8090
      - name: spring-api-worker
        image: spring-api-worker:1.0.0
        ports:
        - containerPort: 8080

